cache:
  paths:
    - node_modules
    - docs/node_modules

before_script:
  - nvm install stable
  - npm prune
  - npm install

test:
  script:
    - npm run test
    - npm run typecheck
    - npm run lint

doc:
  script:
    - cd docs
    - npm install
    - ./deploy.sh
  only:
    - master
  when: on_success
